//------------------------------------------------------------------------------
// <auto-generated>
//     Р­С‚РѕС‚ РєРѕРґ СЃРѕР·РґР°РЅ РїРѕ С€Р°Р±Р»РѕРЅСѓ.
//
//     РР·РјРµРЅРµРЅРёСЏ, РІРЅРѕСЃРёРјС‹Рµ РІ СЌС‚РѕС‚ С„Р°Р№Р» РІСЂСѓС‡РЅСѓСЋ, РјРѕРіСѓС‚ РїСЂРёРІРµСЃС‚Рё Рє РЅРµРїСЂРµРґРІРёРґРµРЅРЅРѕР№ СЂР°Р±РѕС‚Рµ РїСЂРёР»РѕР¶РµРЅРёСЏ.
//     РР·РјРµРЅРµРЅРёСЏ, РІРЅРѕСЃРёРјС‹Рµ РІ СЌС‚РѕС‚ С„Р°Р№Р» РІСЂСѓС‡РЅСѓСЋ, Р±СѓРґСѓС‚ РїРµСЂРµР·Р°РїРёСЃР°РЅС‹ РїСЂРё РїРѕРІС‚РѕСЂРЅРѕРј СЃРѕР·РґР°РЅРёРё РєРѕРґР°.
// </auto-generated>
//------------------------------------------------------------------------------

namespace people
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalogs()
        {
            this.BasketsCatalogs = new HashSet<BasketsCatalogs>();
            this.OrdersCatalogs = new HashSet<OrdersCatalogs>();
        }
    
        public int IdCatalog { get; set; }
        public string Product { get; set; }
        public string Descripton { get; set; }
        public string PhotoPath { get; set; }
        public decimal Price { get; set; }
        public int IdCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasketsCatalogs> BasketsCatalogs { get; set; }
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersCatalogs> OrdersCatalogs { get; set; }
    }
}

