//------------------------------------------------------------------------------
// <auto-generated>
//     Р­С‚РѕС‚ РєРѕРґ СЃРѕР·РґР°РЅ РїРѕ С€Р°Р±Р»РѕРЅСѓ.
//
//     РР·РјРµРЅРµРЅРёСЏ, РІРЅРѕСЃРёРјС‹Рµ РІ СЌС‚РѕС‚ С„Р°Р№Р» РІСЂСѓС‡РЅСѓСЋ, РјРѕРіСѓС‚ РїСЂРёРІРµСЃС‚Рё Рє РЅРµРїСЂРµРґРІРёРґРµРЅРЅРѕР№ СЂР°Р±РѕС‚Рµ РїСЂРёР»РѕР¶РµРЅРёСЏ.
//     РР·РјРµРЅРµРЅРёСЏ, РІРЅРѕСЃРёРјС‹Рµ РІ СЌС‚РѕС‚ С„Р°Р№Р» РІСЂСѓС‡РЅСѓСЋ, Р±СѓРґСѓС‚ РїРµСЂРµР·Р°РїРёСЃР°РЅС‹ РїСЂРё РїРѕРІС‚РѕСЂРЅРѕРј СЃРѕР·РґР°РЅРёРё РєРѕРґР°.
// </auto-generated>
//------------------------------------------------------------------------------

namespace people
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cities()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int IdCity { get; set; }
        public string NameCity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}

