//------------------------------------------------------------------------------
// <auto-generated>
//     Р­С‚РѕС‚ РєРѕРґ СЃРѕР·РґР°РЅ РїРѕ С€Р°Р±Р»РѕРЅСѓ.
//
//     РР·РјРµРЅРµРЅРёСЏ, РІРЅРѕСЃРёРјС‹Рµ РІ СЌС‚РѕС‚ С„Р°Р№Р» РІСЂСѓС‡РЅСѓСЋ, РјРѕРіСѓС‚ РїСЂРёРІРµСЃС‚Рё Рє РЅРµРїСЂРµРґРІРёРґРµРЅРЅРѕР№ СЂР°Р±РѕС‚Рµ РїСЂРёР»РѕР¶РµРЅРёСЏ.
//     РР·РјРµРЅРµРЅРёСЏ, РІРЅРѕСЃРёРјС‹Рµ РІ СЌС‚РѕС‚ С„Р°Р№Р» РІСЂСѓС‡РЅСѓСЋ, Р±СѓРґСѓС‚ РїРµСЂРµР·Р°РїРёСЃР°РЅС‹ РїСЂРё РїРѕРІС‚РѕСЂРЅРѕРј СЃРѕР·РґР°РЅРёРё РєРѕРґР°.
// </auto-generated>
//------------------------------------------------------------------------------

namespace people
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersCatalogs
    {
        public int IdOrderCatalog { get; set; }
        public int IdOrder { get; set; }
        public int IdCatalog { get; set; }
        public int Quantity { get; set; }
    
        public virtual Catalogs Catalogs { get; set; }
        public virtual Orders Orders { get; set; }
    }
}

