//------------------------------------------------------------------------------
// <auto-generated>
//     Р­С‚РѕС‚ РєРѕРґ СЃРѕР·РґР°РЅ РїРѕ С€Р°Р±Р»РѕРЅСѓ.
//
//     РР·РјРµРЅРµРЅРёСЏ, РІРЅРѕСЃРёРјС‹Рµ РІ СЌС‚РѕС‚ С„Р°Р№Р» РІСЂСѓС‡РЅСѓСЋ, РјРѕРіСѓС‚ РїСЂРёРІРµСЃС‚Рё Рє РЅРµРїСЂРµРґРІРёРґРµРЅРЅРѕР№ СЂР°Р±РѕС‚Рµ РїСЂРёР»РѕР¶РµРЅРёСЏ.
//     РР·РјРµРЅРµРЅРёСЏ, РІРЅРѕСЃРёРјС‹Рµ РІ СЌС‚РѕС‚ С„Р°Р№Р» РІСЂСѓС‡РЅСѓСЋ, Р±СѓРґСѓС‚ РїРµСЂРµР·Р°РїРёСЃР°РЅС‹ РїСЂРё РїРѕРІС‚РѕСЂРЅРѕРј СЃРѕР·РґР°РЅРёРё РєРѕРґР°.
// </auto-generated>
//------------------------------------------------------------------------------

namespace people
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrdersCatalogs = new HashSet<OrdersCatalogs>();
        }
    
        public int IdOrder { get; set; }
        public int IdUser { get; set; }
        public int IdStatusOrder { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Price { get; set; }
    
        public virtual StatusOrders StatusOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersCatalogs> OrdersCatalogs { get; set; }
    }
}

