//------------------------------------------------------------------------------
// <auto-generated>
//     Р­С‚РѕС‚ РєРѕРґ СЃРѕР·РґР°РЅ РїРѕ С€Р°Р±Р»РѕРЅСѓ.
//
//     РР·РјРµРЅРµРЅРёСЏ, РІРЅРѕСЃРёРјС‹Рµ РІ СЌС‚РѕС‚ С„Р°Р№Р» РІСЂСѓС‡РЅСѓСЋ, РјРѕРіСѓС‚ РїСЂРёРІРµСЃС‚Рё Рє РЅРµРїСЂРµРґРІРёРґРµРЅРЅРѕР№ СЂР°Р±РѕС‚Рµ РїСЂРёР»РѕР¶РµРЅРёСЏ.
//     РР·РјРµРЅРµРЅРёСЏ, РІРЅРѕСЃРёРјС‹Рµ РІ СЌС‚РѕС‚ С„Р°Р№Р» РІСЂСѓС‡РЅСѓСЋ, Р±СѓРґСѓС‚ РїРµСЂРµР·Р°РїРёСЃР°РЅС‹ РїСЂРё РїРѕРІС‚РѕСЂРЅРѕРј СЃРѕР·РґР°РЅРёРё РєРѕРґР°.
// </auto-generated>
//------------------------------------------------------------------------------

namespace people
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Baskets = new HashSet<Baskets>();
        }
    
        public int IdUser { get; set; }
        public string NameUser { get; set; }
        public int IdRole { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int IdCity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Baskets> Baskets { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Cities Cities { get; set; }
    }
}

